site_name: CoE MLOps Playbook
site_url: ""
site_description: Playbook de Ingeniería de Machine Learning de CoE Analytics
site_author: YPF - CoE Analytics

repo_url: https://github.com/DJuanes/coe-mlops-playbook
edit_uri: ""

nav:
  - Home: index.md
  - Diseño:
    - Producto: Diseño\Producto.md
    - Ingeniería: Diseño\Ingeniería.md
    - Proyecto: Diseño\Proyecto.md
  - Datos:
    - Etiquetado: Datos\Etiquetado.md
    - Exploración: Datos\Exploración.md
    - Preprocesamiento: Datos\Preprocesamiento.md
    - Splitting: Datos\Splitting.md
    - Aumento: Datos\Aumento.md
  - Modelado:
    - Líneas base: Modelado\Líneas base.md
    - Evaluación: Modelado\Evaluación.md
    - Seguimiento de experimentos: Modelado\Seguimiento de experimentos.md
    - Optimización: Modelado\Optimización.md
  - Desarrollo:
    - Empaquetado: Desarrollo\Empaquetado.md
    - Organización: Desarrollo\Organización.md
    - Logging: Desarrollo\Logging.md
    - Documentación: Desarrollo\Documentación.md
    - Estilismo: Desarrollo\Estilismo.md
    - Makefile: Desarrollo\Makefile.md
  - Inferencia:
    - Línea de comando: Inferencia\Línea de comando.md
    - API RESTful: Inferencia\API RESTful.md

theme:
  name: material
  font:
    text: Roboto
  palette:
    primary: blue
  logo: resources/YPF.svg
  favicon: resources/YPF.svg
  features:
    - navigation.instant
    - navigation.indexes

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed




