site_name: CoE MLOps Playbook
site_url: ""
site_description: Playbook de Ingeniería de Machine Learning de CoE Analytics
site_author: YPF - CoE Analytics

repo_url: https://github.com/DJuanes/coe-mlops-playbook
edit_uri: ""

nav:
  - Home: index.md
  - Diseño:
    - Producto: coe-mlops-playbook\Producto.md
    - Ingeniería: coe-mlops-playbook\Ingeniería.md
    - Proyecto: coe-mlops-playbook\Proyecto.md
  - Datos:
    - Etiquetado: coe-mlops-playbook\Etiquetado.md
    - Exploración: coe-mlops-playbook\Exploración.md
    - Preprocesamiento: coe-mlops-playbook\Preprocesamiento.md
    - Splitting: coe-mlops-playbook\Splitting.md
    - Aumento: coe-mlops-playbook\Aumento.md
  - Modelado:
    - Líneas base: coe-mlops-playbook\Líneas base.md
    - Evaluación: coe-mlops-playbook\Evaluación.md
    - Seguimiento de experimentos: coe-mlops-playbook\Seguimiento de experimentos.md
    - Optimización: coe-mlops-playbook\Optimización.md
  - Desarrollo:
    - Empaquetado: coe-mlops-playbook\Empaquetado.md
    - Organización: coe-mlops-playbook\Organización.md
    - Logging: coe-mlops-playbook\Logging.md
    - Documentación: coe-mlops-playbook\Documentación.md
    - Estilismo: coe-mlops-playbook\Estilismo.md
    - Makefile: coe-mlops-playbook\Makefile.md
  - Inferencia:
    - Línea de comando: coe-mlops-playbook\Línea de comando.md
    - API RESTful: coe-mlops-playbook\API RESTful.md

theme:
  name: material
  font:
    text: Roboto
  palette:
    primary: blue
  logo: resources/YPF.svg
  favicon: resources/YPF.svg
  features:
    - navigation.instant
    - navigation.indexes

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed




